name: wisata_pati_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
#  webview_flutter: ^4.2.2
  carousel_slider: ^4.0.0
  url_launcher: ^6.1.12
  equatable: ^2.0.5
  google_fonts: ^5.1.0
  webview_flutter: ^4.2.2
  easy_image_viewer: ^1.2.1

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

